# Generated by Django 2.1.2 on 2018-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drose', '0004_scanresult_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='banners',
            field=models.TextField(blank=True),
        ),
    ]
