# Generated by Django 2.1.2 on 2018-12-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drose', '0007_auto_20181218_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='port',
            field=models.IntegerField(),
        ),
    ]
