# Generated by Django 2.1.2 on 2018-12-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drose', '0009_auto_20181218_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='operation',
            field=models.TextField(blank=True),
        ),
    ]
